name: Run Justfile

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  justfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Nix
        uses: nixbuild/nix-quick-install-action@v29
      - name: Cache Nix store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: ${{ runner.os }}-nix-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: ${{ runner.os }}-nix-
      - name: Use Cachix for Ethereum Nix
        uses: cachix/cachix-action@v15
        with:
          name: ethereum-nix
          extraPullNames: nix-community
      - name: Cache Cargo build
        uses: actions/cache@v4
        with:
          path: |
            target
            ~/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Prepare nix
        run: |
          nix build
          nix flake check --all-systems
      - name: Run Justfile
        run: nix shell -c just
