name: Run Justfile

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  justfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Use Cachix for Ethereum Nix
        uses: cachix/cachix-action@v15
        with:
          name: ethereum-nix
          extraPullNames: nix-community
      - run: nix shell .#just .#cargo-nextest .#reth .#foundry-bin -c just
