name: Run Justfile

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  justfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Use Cachix for Ethereum Nix
        uses: cachix/cachix-action@v15
        with:
          name: ethereum-nix
          extraPullNames: nix-community
      # # Does not work with /nix/store, permission issues
      # - name: Cache Nix Store
      #   uses: actions/cache@v4
      #   with:
      #     path: /nix/store
      #     key: ${{ runner.os }}-nix-${{ hashFiles('**/*.nix') }}
      #     restore-keys: |
      #       ${{ runner.os }}-nix-
      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-
      - name: Cache Cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-
      - run: |
          nix build --quiet .#just .#cargo-nextest .#reth .#foundry-bin
          nix shell .#just .#cargo-nextest .#reth .#foundry-bin -c just
